version: "3.8"

services:
  portainer:
    image: portainer/portainer
    restart: unless-stopped
    container_name: "{{ project_name }}_portainer"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/portainer_data:/data
    networks:
      - ot_network
    labels:
      # Explicitly tell Traefik to expose this container
      - traefik.enable=true
      # - traefik.port=9000 # (it works without, why is it redirected to this port ?)
      # Explicitely tell Watchtower to ignore this container
      # - com.centurylinklabs.watchtower.enable=false
      - traefik.http.routers.portainer.rule=Host(`portainer.{{ app_domain }}`)
      - traefik.http.routers.portainer.tls.certresolver=leresolver
      - traefik.http.routers.portainer.entrypoints=websecure

networks:
  ot_network:
    external: true
